version: '3.1' 
services: 

  jpro-blog: 
    build: 
      context: ./jpro-blog 
      dockerfile: Dockerfile
    container_name: jpro-blog

  jpro-profile: 
    build: 
      context: ./jpro-profile 
      dockerfile: Dockerfile
    container_name: jpro-profile

  jpro-nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: jpro-nginx