version: '3.1' 
services: 

  jpro-mysql8:
    build:
      context: ./mysql
      dockerfile: Dockerfile.local
    container_name: jpro-mysql8
    # platform: linux/arm64/v8 # mac m1용
    # platform: linux/amd64 # mac용
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - jpro-network
    env_file:
      - ./env/.env.local

  jpro-blog: 
    build: 
      context: ./jpro-blog 
      dockerfile: Dockerfile.local
    container_name: jpro-blog
    volumes:
      - ./jpro-blog/src:/var/www/html/jpro-blog
    networks:
      - jpro-network
    env_file:
      - ./env/.env.local

  jpro-profile: 
    build: 
      context: ./jpro-profile 
      dockerfile: Dockerfile.local
    container_name: jpro-profile
    volumes:
      - ./jpro-profile/src:/var/www/html/jpro-profile
    networks:
      - jpro-network

  jpro-nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    container_name: jpro-nginx
    volumes:
      - ./jpro-blog/src:/var/www/html/jpro-blog
      - ./jpro-profile/src:/var/www/html/jpro-profile
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - jpro-network
    env_file:
      - ./env/.env.local

networks:
  jpro-network: