version: '3' 
services: 
  jpro-profile: 
    build: 
      context: ./jpro-profile 
      dockerfile: Dockerfile
    container_name: jpro-profile
    environment: 
      TZ: "Asia/Seoul"
  jpro-blog: 
    build: 
      context: ./jpro-blog 
      dockerfile: Dockerfile
    container_name: jpro-blog
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT  
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      TZ: "Asia/Seoul"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./jpro-profile/src:/var/www/html/jpro-profile
      - ./jpro-blog/src:/var/www/html/jpro-blog
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    environment: 
      TZ: "Asia/Seoul"
