version: '3' 
services: 
  jpro-profile: 
    build: 
      context: ./jpro-profile 
      dockerfile: Dockerfile.dev
    container_name: jpro-profile
    environment: 
      TZ: "Asia/Seoul"
  jpro-blog: 
    build: 
      context: ./jpro-blog 
      dockerfile: Dockerfile.dev
    container_name: jpro-blog
    environment: 
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      access_key_id: $AWS_Access_Key
      secret_access_key: $AWS_Secret_Access_Key
      TZ: "Asia/Seoul"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./jpro-profile/src:/var/www/html/jpro-profile
      - ./jpro-blog/src:/var/www/html/jpro-blog
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    environment: 
      TZ: "Asia/Seoul"
