version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      # - run:
      #   name: Dev Docker Image Bulid
      #   command: |
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-blog-dev ./jpro-blog
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-profile-dev ./jpro-profile
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-nginx-dev ./nginx
      # - run:
      #   name: Dev Docker Image Testing
      #   command: |
      #     docker run -e CI=true $DOCKER_HUB_ID/docker-jpro-blog-dev [test script]
      # - run:
      #     name: Op Docker Image Build
      #     command: |
      #       echo "Build Start"
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-blog ./jpro-blog
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-profile ./jpro-profile
      #       docker build -t $DOCKER_HUB_ID/docker-jpro-nginx ./nginx
      # - run:
      #     name: Image DockerHub Push
      #     command: |
      #       echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
      #       docker push $DOCKER_HUB_ID/docker-jpro-blog
      #       docker push $DOCKER_HUB_ID/docker-jpro-profile
      #       docker push $DOCKER_HUB_ID/docker-jpro-nginx
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update            
            sudo apt-get install -y python3-pip python3-dev build-essential
            sudo pip3 install --upgrade setuptools
            sudo pip3 install awsebcli --upgrade
      # - run:
      #     name: AWS Elastic BeanStalk Deploying
      #     command: |
      #       eb deploy $EB_SERVICE_NAME
      # - run:
      #     name: AWS S3 Uploading
      #     command: |
            