# docker run -it -p 8888:8888 \
# -e GRANT_SUDO=yes --user root \
# --name jupyter-notebook \
# -v $(pwd):/home/jovyan/work jupyter/datascience-notebook \
# jupyter notebook --no-browser --allow-root \
# --port 8888 --ip=0.0.0.0 \
# --NotebookApp.password='argon2:$argon2id$v=19$m=10240,t=10,p=8$b0jiWZjySdtVK03p9OS1fA$wwIJ8J4lTuuK7e9mHGdUsJvIW/Nj1zIJHSUXlcCZm0k' \
# --notebook-dir='~'